### PR TITLE
Use Serverless-webpack V3 RC.1

### PR DESCRIPTION
**Pull request by HyperBrain**
@ktonon @ringods Can you check with my changes in this PR. It should be configured correctly now and works for me.
This PR now uses `serverless-webpack@^3.0.0-rc.1` but with the same configuration it should also work with `^2.2.0`

The fix was to reference the handlers correctly in `serverless.yml` and use `module:rules` in webpack.,config as this is the format used since webpack 2

### CODE REVIEW

**Comment by ktonon** [comment]
@HyperBrain Thanks for the PR. I'm testing this out locally, and while `npm start` looks good, when I try to visit http://localhost:3000 I get

```json
{
  "errorMessage": "Error while loading hello",
  "errorType": "Error",
  "stackTrace": [
    "Error: Cannot find module '/Users/kevin/bc/elm-serverless-demo/.webpack/src/Hello/api'",
    "at Function.Module._resolveFilename (module.js:469:15)",
    "..."
  ]
}
```

**Comment by ktonon** [comment]
Just one more small change: `serverless.yml` line 13:

```yml
custom:
  serverless-offline:
    location: .webpack/service # <--
    dontPrintOutput: true
```

**Comment by ktonon** [comment]
I'll merge the PR and update serverless-offline separately

**Comment by HyperBrain** [comment]
@ktonon Yeah. The `location` option of serverless-offline is quite tricky. Some of the `serverless-webpack` users reported that with sls-webpack V3 offline works even without setting a location at all. Can you check if it works when you remove the location setting?

**Comment by ktonon** [comment]
If I remove the `location` option, I get this when I try to visit a url:

```json
{
  "errorMessage": "Error while loading hello",
  "errorType": "SyntaxError",
  "stackTrace": [
    "/Users/kevin/bc/elm-serverless-demo/src/Hello/API.elm:1",
    "(function (exports, require, module, __filename, __dirname) { port module Hello.API exposing 
    (main)",
    "^^^^^^",
    "SyntaxError: Unexpected identifier",
    "at createScript (vm.js:56:10)",

```

**Comment by ringods** [comment]
@ktonon can you refresh from a clean slate? Dropping the `location` option solved it for me. Created #3 for this.
